# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c009ebf30056f3f46d26b27b402dca12fdfd2765d09a4c2b279a1d7a8233a6f7b067aaa293516df3f6cf4085b1036a04e8854edb1c37902fcb970f9eeebdb0b

test:
  secret_key_base: 64097e130e4b8e6dc6f2845cc18402f2568c4ac308eab1fe8e0aaea8ee651812d649cddd99302fd541876a3650810cd45470b16cae40892fceac2727e6121ab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
